// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web_micro_zhiliao.proto

package web_micro_zhiliao

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Webmicrozhiliao service

func NewWebmicrozhiliaoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Webmicrozhiliao service

type WebmicrozhiliaoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Webmicrozhiliao_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Webmicrozhiliao_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Webmicrozhiliao_BidiStreamService, error)
}

type webmicrozhiliaoService struct {
	c    client.Client
	name string
}

func NewWebmicrozhiliaoService(name string, c client.Client) WebmicrozhiliaoService {
	return &webmicrozhiliaoService{
		c:    c,
		name: name,
	}
}

func (c *webmicrozhiliaoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Webmicrozhiliao.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webmicrozhiliaoService) ClientStream(ctx context.Context, opts ...client.CallOption) (Webmicrozhiliao_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Webmicrozhiliao.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &webmicrozhiliaoServiceClientStream{stream}, nil
}

type Webmicrozhiliao_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type webmicrozhiliaoServiceClientStream struct {
	stream client.Stream
}

func (x *webmicrozhiliaoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webmicrozhiliaoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *webmicrozhiliaoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Webmicrozhiliao_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Webmicrozhiliao.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &webmicrozhiliaoServiceServerStream{stream}, nil
}

type Webmicrozhiliao_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type webmicrozhiliaoServiceServerStream struct {
	stream client.Stream
}

func (x *webmicrozhiliaoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webmicrozhiliaoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webmicrozhiliaoService) BidiStream(ctx context.Context, opts ...client.CallOption) (Webmicrozhiliao_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Webmicrozhiliao.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &webmicrozhiliaoServiceBidiStream{stream}, nil
}

type Webmicrozhiliao_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type webmicrozhiliaoServiceBidiStream struct {
	stream client.Stream
}

func (x *webmicrozhiliaoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *webmicrozhiliaoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Webmicrozhiliao service

type WebmicrozhiliaoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Webmicrozhiliao_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Webmicrozhiliao_ServerStreamStream) error
	BidiStream(context.Context, Webmicrozhiliao_BidiStreamStream) error
}

func RegisterWebmicrozhiliaoHandler(s server.Server, hdlr WebmicrozhiliaoHandler, opts ...server.HandlerOption) error {
	type webmicrozhiliao interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Webmicrozhiliao struct {
		webmicrozhiliao
	}
	h := &webmicrozhiliaoHandler{hdlr}
	return s.Handle(s.NewHandler(&Webmicrozhiliao{h}, opts...))
}

type webmicrozhiliaoHandler struct {
	WebmicrozhiliaoHandler
}

func (h *webmicrozhiliaoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.WebmicrozhiliaoHandler.Call(ctx, in, out)
}

func (h *webmicrozhiliaoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.WebmicrozhiliaoHandler.ClientStream(ctx, &webmicrozhiliaoClientStreamStream{stream})
}

type Webmicrozhiliao_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type webmicrozhiliaoClientStreamStream struct {
	stream server.Stream
}

func (x *webmicrozhiliaoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *webmicrozhiliaoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WebmicrozhiliaoHandler.ServerStream(ctx, m, &webmicrozhiliaoServerStreamStream{stream})
}

type Webmicrozhiliao_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type webmicrozhiliaoServerStreamStream struct {
	stream server.Stream
}

func (x *webmicrozhiliaoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *webmicrozhiliaoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.WebmicrozhiliaoHandler.BidiStream(ctx, &webmicrozhiliaoBidiStreamStream{stream})
}

type Webmicrozhiliao_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type webmicrozhiliaoBidiStreamStream struct {
	stream server.Stream
}

func (x *webmicrozhiliaoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *webmicrozhiliaoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *webmicrozhiliaoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *webmicrozhiliaoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *webmicrozhiliaoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
