// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/web_micro_zhiliao.proto

package web_micro_zhiliao

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Webmicrozhiliao service

func NewWebmicrozhiliaoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Webmicrozhiliao service

type WebmicrozhiliaoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
}

type webmicrozhiliaoService struct {
	c    client.Client
	name string
}

func NewWebmicrozhiliaoService(name string, c client.Client) WebmicrozhiliaoService {
	return &webmicrozhiliaoService{
		c:    c,
		name: name,
	}
}

func (c *webmicrozhiliaoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Webmicrozhiliao.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Webmicrozhiliao service

type WebmicrozhiliaoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
}

func RegisterWebmicrozhiliaoHandler(s server.Server, hdlr WebmicrozhiliaoHandler, opts ...server.HandlerOption) error {
	type webmicrozhiliao interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
	}
	type Webmicrozhiliao struct {
		webmicrozhiliao
	}
	h := &webmicrozhiliaoHandler{hdlr}
	return s.Handle(s.NewHandler(&Webmicrozhiliao{h}, opts...))
}

type webmicrozhiliaoHandler struct {
	WebmicrozhiliaoHandler
}

func (h *webmicrozhiliaoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.WebmicrozhiliaoHandler.Call(ctx, in, out)
}
