// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/seckill_micro_zhiliao.proto

package seckill_micro_zhiliao

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Seckillmicrozhiliao service

func NewSeckillmicrozhiliaoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Seckillmicrozhiliao service

type SeckillmicrozhiliaoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Seckillmicrozhiliao_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Seckillmicrozhiliao_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Seckillmicrozhiliao_BidiStreamService, error)
}

type seckillmicrozhiliaoService struct {
	c    client.Client
	name string
}

func NewSeckillmicrozhiliaoService(name string, c client.Client) SeckillmicrozhiliaoService {
	return &seckillmicrozhiliaoService{
		c:    c,
		name: name,
	}
}

func (c *seckillmicrozhiliaoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Seckillmicrozhiliao.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillmicrozhiliaoService) ClientStream(ctx context.Context, opts ...client.CallOption) (Seckillmicrozhiliao_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Seckillmicrozhiliao.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &seckillmicrozhiliaoServiceClientStream{stream}, nil
}

type Seckillmicrozhiliao_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type seckillmicrozhiliaoServiceClientStream struct {
	stream client.Stream
}

func (x *seckillmicrozhiliaoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *seckillmicrozhiliaoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *seckillmicrozhiliaoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Seckillmicrozhiliao_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Seckillmicrozhiliao.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &seckillmicrozhiliaoServiceServerStream{stream}, nil
}

type Seckillmicrozhiliao_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type seckillmicrozhiliaoServiceServerStream struct {
	stream client.Stream
}

func (x *seckillmicrozhiliaoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *seckillmicrozhiliaoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *seckillmicrozhiliaoService) BidiStream(ctx context.Context, opts ...client.CallOption) (Seckillmicrozhiliao_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Seckillmicrozhiliao.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &seckillmicrozhiliaoServiceBidiStream{stream}, nil
}

type Seckillmicrozhiliao_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type seckillmicrozhiliaoServiceBidiStream struct {
	stream client.Stream
}

func (x *seckillmicrozhiliaoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *seckillmicrozhiliaoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Seckillmicrozhiliao service

type SeckillmicrozhiliaoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Seckillmicrozhiliao_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Seckillmicrozhiliao_ServerStreamStream) error
	BidiStream(context.Context, Seckillmicrozhiliao_BidiStreamStream) error
}

func RegisterSeckillmicrozhiliaoHandler(s server.Server, hdlr SeckillmicrozhiliaoHandler, opts ...server.HandlerOption) error {
	type seckillmicrozhiliao interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Seckillmicrozhiliao struct {
		seckillmicrozhiliao
	}
	h := &seckillmicrozhiliaoHandler{hdlr}
	return s.Handle(s.NewHandler(&Seckillmicrozhiliao{h}, opts...))
}

type seckillmicrozhiliaoHandler struct {
	SeckillmicrozhiliaoHandler
}

func (h *seckillmicrozhiliaoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.SeckillmicrozhiliaoHandler.Call(ctx, in, out)
}

func (h *seckillmicrozhiliaoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.SeckillmicrozhiliaoHandler.ClientStream(ctx, &seckillmicrozhiliaoClientStreamStream{stream})
}

type Seckillmicrozhiliao_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type seckillmicrozhiliaoClientStreamStream struct {
	stream server.Stream
}

func (x *seckillmicrozhiliaoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *seckillmicrozhiliaoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SeckillmicrozhiliaoHandler.ServerStream(ctx, m, &seckillmicrozhiliaoServerStreamStream{stream})
}

type Seckillmicrozhiliao_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type seckillmicrozhiliaoServerStreamStream struct {
	stream server.Stream
}

func (x *seckillmicrozhiliaoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *seckillmicrozhiliaoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.SeckillmicrozhiliaoHandler.BidiStream(ctx, &seckillmicrozhiliaoBidiStreamStream{stream})
}

type Seckillmicrozhiliao_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type seckillmicrozhiliaoBidiStreamStream struct {
	stream server.Stream
}

func (x *seckillmicrozhiliaoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *seckillmicrozhiliaoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *seckillmicrozhiliaoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *seckillmicrozhiliaoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *seckillmicrozhiliaoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
