// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user_micro_zhiliao.proto

package user_micro_zhiliao

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Usermicrozhiliao service

func NewUsermicrozhiliaoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Usermicrozhiliao service

type UsermicrozhiliaoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Usermicrozhiliao_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Usermicrozhiliao_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Usermicrozhiliao_BidiStreamService, error)
}

type usermicrozhiliaoService struct {
	c    client.Client
	name string
}

func NewUsermicrozhiliaoService(name string, c client.Client) UsermicrozhiliaoService {
	return &usermicrozhiliaoService{
		c:    c,
		name: name,
	}
}

func (c *usermicrozhiliaoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Usermicrozhiliao.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usermicrozhiliaoService) ClientStream(ctx context.Context, opts ...client.CallOption) (Usermicrozhiliao_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Usermicrozhiliao.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &usermicrozhiliaoServiceClientStream{stream}, nil
}

type Usermicrozhiliao_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type usermicrozhiliaoServiceClientStream struct {
	stream client.Stream
}

func (x *usermicrozhiliaoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *usermicrozhiliaoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *usermicrozhiliaoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Usermicrozhiliao_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Usermicrozhiliao.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &usermicrozhiliaoServiceServerStream{stream}, nil
}

type Usermicrozhiliao_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type usermicrozhiliaoServiceServerStream struct {
	stream client.Stream
}

func (x *usermicrozhiliaoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *usermicrozhiliaoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *usermicrozhiliaoService) BidiStream(ctx context.Context, opts ...client.CallOption) (Usermicrozhiliao_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Usermicrozhiliao.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &usermicrozhiliaoServiceBidiStream{stream}, nil
}

type Usermicrozhiliao_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type usermicrozhiliaoServiceBidiStream struct {
	stream client.Stream
}

func (x *usermicrozhiliaoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *usermicrozhiliaoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Usermicrozhiliao service

type UsermicrozhiliaoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Usermicrozhiliao_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Usermicrozhiliao_ServerStreamStream) error
	BidiStream(context.Context, Usermicrozhiliao_BidiStreamStream) error
}

func RegisterUsermicrozhiliaoHandler(s server.Server, hdlr UsermicrozhiliaoHandler, opts ...server.HandlerOption) error {
	type usermicrozhiliao interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Usermicrozhiliao struct {
		usermicrozhiliao
	}
	h := &usermicrozhiliaoHandler{hdlr}
	return s.Handle(s.NewHandler(&Usermicrozhiliao{h}, opts...))
}

type usermicrozhiliaoHandler struct {
	UsermicrozhiliaoHandler
}

func (h *usermicrozhiliaoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.UsermicrozhiliaoHandler.Call(ctx, in, out)
}

func (h *usermicrozhiliaoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.UsermicrozhiliaoHandler.ClientStream(ctx, &usermicrozhiliaoClientStreamStream{stream})
}

type Usermicrozhiliao_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type usermicrozhiliaoClientStreamStream struct {
	stream server.Stream
}

func (x *usermicrozhiliaoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *usermicrozhiliaoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.UsermicrozhiliaoHandler.ServerStream(ctx, m, &usermicrozhiliaoServerStreamStream{stream})
}

type Usermicrozhiliao_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type usermicrozhiliaoServerStreamStream struct {
	stream server.Stream
}

func (x *usermicrozhiliaoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *usermicrozhiliaoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.UsermicrozhiliaoHandler.BidiStream(ctx, &usermicrozhiliaoBidiStreamStream{stream})
}

type Usermicrozhiliao_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type usermicrozhiliaoBidiStreamStream struct {
	stream server.Stream
}

func (x *usermicrozhiliaoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *usermicrozhiliaoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *usermicrozhiliaoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *usermicrozhiliaoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *usermicrozhiliaoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
