// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/product_micro_zhiliao.proto

package product_micro_zhiliao

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Productmicrozhiliao service

func NewProductmicrozhiliaoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Productmicrozhiliao service

type ProductmicrozhiliaoService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Productmicrozhiliao_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Productmicrozhiliao_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Productmicrozhiliao_BidiStreamService, error)
}

type productmicrozhiliaoService struct {
	c    client.Client
	name string
}

func NewProductmicrozhiliaoService(name string, c client.Client) ProductmicrozhiliaoService {
	return &productmicrozhiliaoService{
		c:    c,
		name: name,
	}
}

func (c *productmicrozhiliaoService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Productmicrozhiliao.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productmicrozhiliaoService) ClientStream(ctx context.Context, opts ...client.CallOption) (Productmicrozhiliao_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Productmicrozhiliao.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productmicrozhiliaoServiceClientStream{stream}, nil
}

type Productmicrozhiliao_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type productmicrozhiliaoServiceClientStream struct {
	stream client.Stream
}

func (x *productmicrozhiliaoServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productmicrozhiliaoServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *productmicrozhiliaoService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Productmicrozhiliao_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Productmicrozhiliao.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &productmicrozhiliaoServiceServerStream{stream}, nil
}

type Productmicrozhiliao_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type productmicrozhiliaoServiceServerStream struct {
	stream client.Stream
}

func (x *productmicrozhiliaoServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productmicrozhiliaoServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productmicrozhiliaoService) BidiStream(ctx context.Context, opts ...client.CallOption) (Productmicrozhiliao_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Productmicrozhiliao.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &productmicrozhiliaoServiceBidiStream{stream}, nil
}

type Productmicrozhiliao_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type productmicrozhiliaoServiceBidiStream struct {
	stream client.Stream
}

func (x *productmicrozhiliaoServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *productmicrozhiliaoServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Productmicrozhiliao service

type ProductmicrozhiliaoHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Productmicrozhiliao_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Productmicrozhiliao_ServerStreamStream) error
	BidiStream(context.Context, Productmicrozhiliao_BidiStreamStream) error
}

func RegisterProductmicrozhiliaoHandler(s server.Server, hdlr ProductmicrozhiliaoHandler, opts ...server.HandlerOption) error {
	type productmicrozhiliao interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Productmicrozhiliao struct {
		productmicrozhiliao
	}
	h := &productmicrozhiliaoHandler{hdlr}
	return s.Handle(s.NewHandler(&Productmicrozhiliao{h}, opts...))
}

type productmicrozhiliaoHandler struct {
	ProductmicrozhiliaoHandler
}

func (h *productmicrozhiliaoHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ProductmicrozhiliaoHandler.Call(ctx, in, out)
}

func (h *productmicrozhiliaoHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ProductmicrozhiliaoHandler.ClientStream(ctx, &productmicrozhiliaoClientStreamStream{stream})
}

type Productmicrozhiliao_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type productmicrozhiliaoClientStreamStream struct {
	stream server.Stream
}

func (x *productmicrozhiliaoClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *productmicrozhiliaoHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProductmicrozhiliaoHandler.ServerStream(ctx, m, &productmicrozhiliaoServerStreamStream{stream})
}

type Productmicrozhiliao_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type productmicrozhiliaoServerStreamStream struct {
	stream server.Stream
}

func (x *productmicrozhiliaoServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *productmicrozhiliaoHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ProductmicrozhiliaoHandler.BidiStream(ctx, &productmicrozhiliaoBidiStreamStream{stream})
}

type Productmicrozhiliao_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type productmicrozhiliaoBidiStreamStream struct {
	stream server.Stream
}

func (x *productmicrozhiliaoBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *productmicrozhiliaoBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *productmicrozhiliaoBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *productmicrozhiliaoBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *productmicrozhiliaoBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
